# Generated by Django 5.0.1 on 2024-05-07 07:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('career_opportunities', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('dress_code', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('program_content', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
            ],
        ),
    ]
