# Generated by Django 5.0.1 on 2024-05-07 11:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_anti_ragging_cell_legal_aid_cell_notice_board_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Important_Links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Principals_Desk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
            ],
        ),
    ]
