# Generated by Django 5.0.1 on 2024-05-07 11:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_admission_important_links_personal_interview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='career_opportunities',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='dress_code',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='program_content',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
