# Generated by Django 5.0.1 on 2024-05-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_rename_contact_contactdetail_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('high_school', models.CharField(max_length=15)),
                ('intermediate', models.CharField(max_length=15)),
                ('graduation', models.CharField(max_length=15)),
                ('post_graduation', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('applying_for', models.CharField(max_length=100)),
            ],
        ),
    ]
