# Generated by Django 5.0.1 on 2024-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_admission_prospectus_alter_notice_board_downloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday_List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
